<?php $this->title = $post->title; ?>
<section class="breadcrumb-section type2 parallax-window" data-parallax="scroll" data-speed="0.3" data-image-src="<?php echo Yii::$app->getUrlManager()->getBaseUrl() ?>/images/bg_s1.png" style="background: transparent;">
    <div class="breadcrumb">
        <div class="container">
            <div id="breadcrumbs">
            	<span typeof="v:Breadcrumb"><a href="#" property="v:title">Trang chủ</a> » 
            	<span class="breadcrumb_last"><?php echo $post->title; ?></span>
            </div>
        </div>
    </div>
</section>    
<!-- Noi dung chinh-->
<div id="content-single" class="wrapper-content">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div id="content-single">
                    <div class="entry-title"><?php echo $post->title; ?></div>
                    <?php echo '<div class="entry-content">'.$post->description.'</div>'; ?>
                </div>
            </div>
                        <!-- Right-sidebar -->
            <div class="col-md-4">
                <div id="right-sidebar">
                    <aside id="rpwe_widget-2" class="widget rpwe_widget recent-posts-extended">
                        <h3 class="widget-title"><span>Tin tức</span></h3>
                        <div class="rpwe-block ">
                            <ul class="rpwe-ul">
                            <?php foreach ($List_Tintuc as $tintuc ): ?>
                                <li class="rpwe-li rpwe-clearfix">
                                    <a class="rpwe-img" href="<?php echo $tintuc->getLink(); ?>" rel="bookmark"><img src="<?php echo $tintuc->getLinkAnh(); ?>" alt="" class="img-responsive"></a>
                                    <h3 class="rpwe-title"><a href="<?php echo $tintuc->getLink(); ?>" rel="bookmark"><?php echo $tintuc->title ?></a></h3>
                                    <time class="rpwe-time published">Ngày <?php echo $tintuc->getTime() ?></time>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        </div>
                        <!-- Generated by http://wordpress.org/plugins/recent-posts-widget-extended/ -->
                    </aside>
                    <aside>
                        <h3 class="widget-title"><span>Fanpage</span></h3>
                        <div class="fb-page" data-href="https://www.facebook.com/dieutribenhdaudaday/?fref=ts" data-tabs="timeline" data-width="500" data-height="200" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/dieutribenhdaudaday/?fref=ts" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/dieutribenhdaudaday/?fref=ts">Curmin Lead -  Dập tắt cơn đau dạ dày sau 2 tuần</a></blockquote></div>
                    </aside>
                    <aside>
                        <h3 class="widget-title"><span>Video</span></h3>
                        <div class="box_video">
                            <h3><a href="#">Video</a></h3>
                            
                            <a data-toggle="modal" href='#modal-id'>
                                <div class="box-content-video">
                                    <img src="images/video.jpg" class="img-responsive" />
                                </div>
                            </a>
                        </div>                            
                        <div class="modal fade" id="modal-id">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Video</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="video-container">
                                            <iframe width="854" height="480" src="https://www.youtube.com/embed/H3noeWE-Bxo" frameborder="0" allowfullscreen></iframe>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
            <!-- Right-sidebar -->
        </div>
    </div>
</div>